# -*- coding: utf-8 -*-
"""Image generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4YeYIgUzdmbrRV5urWMJuXdjFrXZ6j-
"""

import torch
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

!pip install -q -U diffusers transformers accelerate safetensors

import torch
from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    use_safetensors=True
)

pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to("cuda")
pipe.enable_attention_slicing()

print("Model loaded successfully on", torch.cuda.get_device_name(0))

prompt = "ultra-detailed portrait of a red fox wearing a tiny scarf, cinematic lighting, 35mm"
negative_prompt = "blurry, lowres, jpeg artifacts, text, watermark"

generator = torch.Generator(device="cuda").manual_seed(42)

image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=20,
    guidance_scale=7.0,
    height=512,
    width=512,
    generator=generator
).images[0]

image

prompt = "ultra-detailed portrait of a red fox wearing a tiny scarf, cinematic lighting, 35mm"
negative_prompt = "blurry, lowres, jpeg artifacts, text, watermark"

generator = torch.Generator(device="cuda").manual_seed(42)

image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=30,
    guidance_scale=7.5,
    height=512,
    width=512,
    generator=generator
).images[0]

image

prompt = "a focused student sitting alone in a classroom, reading a book, soft natural lighting, realistic, high detail, depth of field"
negative_prompt = "blurry, lowres, bad anatomy, distorted, extra limbs, text, watermark"

generator = torch.Generator(device="cuda").manual_seed(123)

image_with_neg = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=20,
    guidance_scale=7.0,
    height=512,
    width=512,
    generator=generator
).images[0]

image_with_neg

generator = torch.Generator(device="cuda").manual_seed(123)

image_without_neg = pipe(
    prompt=prompt,
    num_inference_steps=20,
    guidance_scale=7.0,
    height=512,
    width=512,
    generator=generator
).images[0]

image_without_neg

prompt = "a student sitting alone at a classroom desk, clearly reading an open book in front of them, eyes directed at the book, both hands resting naturally near the pages, realistic classroom scene, soft natural window light, high detail, photorealistic"
negative_prompt = "sleeping, looking out the window, blurry, lowres, distorted hands, extra fingers, malformed hands, bad anatomy, warped desk, text, watermark"

generator = torch.Generator(device="cuda").manual_seed(123)

image_with_neg = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=20,
    guidance_scale=7.0,
    height=512,
    width=512,
    generator=generator
).images[0]

image_with_neg

